# Generated by Django 3.1.7 on 2021-02-22 15:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('LOG', 'Backlog'), ('CRT', 'Created'), ('WIP', 'In Progress'), ('DON', 'Done')], default='CRT', max_length=3)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2021, 2, 20, 22, 8, 30, 105668))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created', 'due_date'],
            },
        ),
    ]
