# Generated by Django 3.1.7 on 2021-03-03 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 23, 39, 22, 54842)),
        ),
    ]
