# Generated by Django 3.1.7 on 2021-03-16 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20210313_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 22, 31, 58, 253683)),
        ),
    ]
