# Generated by Django 3.1.7 on 2021-03-27 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20210327_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 16, 16, 29, 140142, tzinfo=utc)),
        ),
    ]
