# Generated by Django 3.1.7 on 2021-05-12 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20210327_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 10, 27, 49, 970055, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(tasks.models.TaskStatus['BACKLOG'], 'LOG'), (tasks.models.TaskStatus['CREATED'], 'CRT'), (tasks.models.TaskStatus['IN_PROGRESS'], 'WIP'), (tasks.models.TaskStatus['DONE'], 'DON')], default=tasks.models.TaskStatus['CREATED'], max_length=3),
        ),
    ]
