# Generated by Django 3.1.7 on 2021-05-14 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20210512_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 5, 34, 0, 278959, tzinfo=utc)),
        ),
    ]
