# Generated by Django 3.1.7 on 2021-05-15 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import enumfields.fields
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20210514_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 13, 26, 33, 553496, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=enumfields.fields.EnumField(enum=tasks.models.TaskStatus, max_length=3),
        ),
    ]
