# Generated by Django 3.1.7 on 2021-05-15 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20210515_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 13, 43, 59, 609148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('LOG', 'Backlog'), ('CRT', 'Created'), ('WIP', 'In Progress'), ('DON', 'Done')], default='CRT', max_length=3),
        ),
    ]
