# Generated by Django 3.1.7 on 2021-05-15 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20210515_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 13, 56, 45, 452781, tzinfo=utc)),
        ),
    ]
