# Generated by Django 3.1.7 on 2021-06-05 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_auto_20210605_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 15, 26, 46, 199640, tzinfo=utc)),
        ),
    ]
